[phases.setup]
nixPkgs = ['nodejs-22_x', 'yarn-1_x']

[phases.install]
cmds = ['cd Formularios-dev && yarn install --frozen-lockfile']

[phases.build]
cmds = ['cd Formularios-dev && yarn run build']

[start]
cmd = 'cd Formularios-dev && yarn run start'